name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Run tests when a PR is made to 'main'

jobs:
  test:
    name: test  # Job must be named exactly 'test'
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full repo history is cloned

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Match the project's Python version

      - name: Install Dependencies
        run: |
          python -m venv venv --system-site-packages  # ✅ Use global site packages if needed
          source venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "API_PREFIX=/api/v1" >> $GITHUB_ENV  # ✅ Ensure API prefix is set
          echo "✅ API_PREFIX set to $API_PREFIX"

      - name: Verify Installed Packages
        run: |
          source venv/bin/activate
          pip list  # ✅ Print installed dependencies

      - name: Verify Files
        run: |
          ls -la  # ✅ List all files to confirm project structure
          echo "Checking if main.py exists..."
          cat main.py || echo "❌ main.py NOT FOUND!"

      - name: Debug main.py File
        run: |
          echo "🔍 Checking main.py contents..."
          cat main.py || echo "❌ main.py not found"

      - name: Run Tests with pytest
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PWD  # Ensure Python finds main.py
          pytest -v --tb=short  # Run all tests with detailed output
