name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy FastAPI App
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov uvicorn

      # 4. Debug File Structure and Python Path
      - name: Debug File Structure
        run: |
          ls -l
          find . -type d
          find . -name "*.py"
          source venv/bin/activate
          python -c "import sys; print(sys.path)"

      # 5. Run Tests with Coverage
      - name: Run Tests Before Deployment
        run: |
          source venv/bin/activate
          pytest --cov=app --cov-report=term-missing || exit 1

      # 6. Ensure `__init__.py` Exists
      - name: Ensure `__init__.py` is Present
        run: |
          touch app/__init__.py  # Ensure it's a Python module

      # 7. Start FastAPI Server
      - name: Start FastAPI Server
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PWD  # Ensure correct import path
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload > fastapi.log 2>&1 &

      # 8. Wait for FastAPI to Start
      - name: Wait for FastAPI to be Ready
        run: |
          for i in {1..20}; do
            if curl -sSf http://localhost:8000/docs > /dev/null; then
              echo "✅ FastAPI is up"
              exit 0
            fi
            echo "⏳ Waiting for FastAPI to start..."
            sleep 3
          done
          echo "❌ FastAPI did not start in time. Debugging logs:"
          tail -n 20 fastapi.log
          exit 1

      # 9. Test Stage2 Endpoint
      - name: Run Stage2 Endpoint Test
        run: |
          curl -sSf http://localhost:8000/stage2 > /dev/null || (echo "Stage2 endpoint test failed" && exit 1)

      # 10. Deploy to Server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
            cd /path/to/your/app  # ⚠️ REPLACE WITH YOUR ACTUAL DEPLOYMENT PATH
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-app
            sudo systemctl restart nginx
          EOF
