name: CD Pipeline

on:
  push:
    branches:
      - main  # Run deployment ONLY when changes are pushed to main

jobs:
  deploy:
    name: deploy  # Job must be named exactly 'deploy'
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Pull the latest code from the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Match the project's Python version

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests Before Deployment
        run: |
          source venv/bin/activate
          pytest  # Run all tests to ensure everything is working

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
            set -e  # Exit if any command fails

            echo "🚀 Switching to application directory"
            cd /path/to/your/app  # Navigate to deployment directory

            echo "🔄 Stashing any local changes to prevent conflicts"
            git reset --hard origin/main  # Ensure a clean working directory
            git pull origin main --rebase  # Ensure the latest changes are fetched

            echo "📦 Installing dependencies"
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install new dependencies if any

            echo "🔄 Restarting FastAPI Application"
            sudo systemctl restart fastapi-app  # Restart the FastAPI service

            echo "🔄 Restarting Nginx"
            sudo systemctl restart nginx  # Restart Nginx if needed

            echo "✅ Deployment Complete!"
          EOF
