name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests Before Deployment
        run: |
          source venv/bin/activate
          pytest

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
            # Navigate to the correct application directory
            cd /home/$SERVER_USER/fastapi-book-project

            # Pull latest changes
            git pull origin main

            # Update virtual environment
            python -m venv venv || true
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Restart the application service
            sudo systemctl restart fastapi-app

            # Verify the service is running
            systemctl is-active --quiet fastapi-app && echo "Service is running" || echo "Service failed to start"
          EOF

      - name: Verify Deployment
        run: |
          # Wait for the service to be fully up
          sleep 10
          # Test the endpoint
          curl -f http://${{ secrets.SERVER_IP }}/stage2 || exit 1