name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy FastAPI App
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov uvicorn  # Ensure uvicorn is installed

      # 4️⃣ Debug File Structure and Python Path
      - name: Debug File Structure
        run: |
          ls -l
          find . -type d
          find . -name "*.py"
          source venv/bin/activate
          python -c "import sys; print(sys.path)"

      # 5️⃣ Run Tests with Coverage
      - name: Run Tests Before Deployment
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PWD  # Ensure Python can find main.py
          pytest tests --cov=main --cov-report=term-missing || exit 1

      # 6️⃣ Start FastAPI Server and Print Logs
      - name: Start FastAPI Server
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PWD  # Ensure FastAPI can find modules
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > fastapi.log 2>&1 &
          sleep 3  # Give FastAPI time to start
          cat fastapi.log || echo "❌ No logs found"

      # 7️⃣ Wait for FastAPI to Start (Using 127.0.0.1 Instead of localhost)
      - name: Wait for FastAPI to be Ready
        run: |
          for i in {1..20}; do
            if curl -sSf http://127.0.0.1:8000/docs > /dev/null; then
              echo "✅ FastAPI is up"
              exit 0
            fi
            echo "⏳ Waiting for FastAPI to start..."
            sleep 3
          done
          echo "❌ FastAPI did not start in time. Debugging logs:"
          cat fastapi.log || echo "❌ No logs found"
          exit 1

      # 8️⃣ Test Stage2 Endpoint
      - name: Run Stage2 Endpoint Test
        run: |
          curl -sSf http://127.0.0.1:8000/stage2 > /dev/null || (echo "Stage2 endpoint test failed" && exit 1)

      # 9️⃣ Deploy to Server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
            cd /path/to/your/app  # ⚠️ REPLACE WITH YOUR ACTUAL DEPLOYMENT PATH
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-app
            sudo systemctl restart nginx
          EOF
