name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy FastAPI App
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # 4. Debug Virtual Environment (Check if it's activated properly)
      - name: Debug Virtual Environment
        run: |
          source venv/bin/activate
          which python
          python --version
          pip list

      # 5. Run Tests with Coverage
      - name: Run Tests Before Deployment
        run: |
          source venv/bin/activate
          pytest --cov=app --cov-report=term-missing || exit 1

      # 6. Start FastAPI in Background (Ensure it's accessible)
      - name: Start FastAPI Server
        run: |
          source venv/bin/activate
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &

      # 7. Wait for FastAPI to Start
      - name: Wait for FastAPI to be Ready
        run: |
          for i in {1..10}; do
            curl -sSf http://localhost:8000/docs && echo "FastAPI is up" && exit 0
            echo "Waiting for FastAPI..."
            sleep 3
          done
          echo "FastAPI did not start in time" && exit 1

      # 8. Test Stage2 Endpoint
      - name: Run Stage2 Endpoint Test
        run: |
          curl -sSf http://localhost:8000/stage2 > /dev/null || (echo "Stage2 endpoint test failed" && exit 1)

      # 9. Deploy to Server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
            cd /path/to/your/app  # ⚠️ REPLACE WITH YOUR ACTUAL DEPLOYMENT PATH
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-app
            sudo systemctl restart nginx
          EOF
