name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy FastAPI App
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies (Force Clean Install)
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir pytest pytest-cov uvicorn  # Ensure uvicorn is installed

      # 4️⃣ Debug main.py File (Check for corruption)
      - name: Debug main.py File
        run: |
          cat main.py || echo "❌ main.py not found"

      # 5️⃣ Run Tests with Debugging
      - name: Run Tests Before Deployment
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PWD
          pytest -v --tb=short || exit 1  # Verbose test output

      # 6️⃣ Start FastAPI Server (Production Mode)
      - name: Start FastAPI Server
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PWD
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 --reload > fastapi.log 2>&1 &
          sleep 3  # Give FastAPI time to start
          cat fastapi.log || echo "❌ No logs found"

      # 7️⃣ Wait for FastAPI to be Ready
      - name: Wait for FastAPI to be Ready
        run: |
          for i in {1..20}; do
            if curl -sSf http://127.0.0.1:8000/docs > /dev/null; then
              echo "✅ FastAPI is up"
              exit 0
            fi
            echo "⏳ Waiting for FastAPI to start..."
            sleep 3
          done
          echo "❌ FastAPI did not start in time. Debugging logs:"
          cat fastapi.log || echo "❌ No logs found"
          exit 1

      # 8️⃣ Deploy to Production Server
      - name: Deploy to Production Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
            cd /path/to/your/app  # ⚠️ REPLACE WITH YOUR ACTUAL DEPLOYMENT PATH
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-app  # Restart FastAPI
            sudo systemctl restart nginx  # Restart Nginx if used
          EOF
